# Generated by Django 5.2.6 on 2025-09-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='TasksModel',
        ),
    ]
